config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
          # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Default Scrivito routes. Adapt them to change the routing of CMS objects.
  # See the documentation of 'scrivito_route' for a detailed description.
  scrivito_route '/', using: 'homepage'
  scrivito_route '(/)(*slug-):id', using: 'slug_id'
  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
    resources :products do
      member do
        post 'create_scrivito_obj'
      end
    end
  end

  scrivito_route '/*permalink', using: 'permalink', format: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/download.rb
class Download < Obj
  attribute :blob, :binary
  attribute :tags, :stringlist
end

app/models/headline_widget.rb
class HeadlineWidget < Widget
  attribute :headline, :string
end

app/models/homepage.rb
class Homepage < Obj
  attribute :title, :string
  attribute :body, :widgetlist
  attribute :child_order, :referencelist
  attribute :tags, :stringlist

  # global content
  attribute :logo, :reference
  attribute :footer, :widgetlist
  attribute :products_sidebar, :widgetlist
end

app/models/image.rb
class Image < Obj
  attribute :blob, :binary
  attribute :tags, :stringlist

  # activate image resizing and optimization
  def apply_image_transformation?
    true
  end
end

app/models/image_widget.rb
class ImageWidget < Widget
  attribute :image, :reference
end

app/models/obj.rb
class Obj < Scrivito::BasicObj
end

app/models/page.rb
class Page < Obj
  attribute :title, :string
  attribute :body, :widgetlist
  attribute :child_order, :referencelist
  attribute :tags, :stringlist
end

app/models/product_data.rb
class ProductData < Obj
  attribute :body, :widgetlist
  attribute :product_id, :string

  def self.scrivito_id_for_product(product)
    Digest::SHA1.hexdigest("product-#{product.id}")[0...16]
  end

  def self.create_for(product)
    create(_id: scrivito_id_for_product(product), product_id: product.id)
  end

  def self.find_for(product)
    find(scrivito_id_for_product(product))
  end

  

end

app/models/solidus_products_widget.rb
class SolidusProductsWidget < Widget
  attribute :product_ids, :stringlist

  def products
    return [] unless product_ids.present?

    spree_products = Spree::Product.find(product_ids)

    # Spree API may return products in different order!
    product_ids.map { |id| spree_products.detect { |p| p.id.to_s == id } }
  end
end

app/models/solidus_scrivito_user.rb
module SolidusScrivitoUser
  def self.to_scrivito_user(solidus_user)
    return if solidus_user.blank?
    return unless solidus_user.admin?

    Scrivito::User.define(solidus_user.id.to_s) do |user|
      user.description {
        solidus_user.login
      }
      user.suggest_users do |input|
        Spree::User.search(login: input).result.map do |found_user|
          to_scrivito_user(found_user)
        end
      end

      Scrivito::User::VERBS.each { |can_have| user.can_always(can_have, :workspace) }
    end
  end
end

app/models/text_widget.rb
class TextWidget < Widget
  attribute :text, :html
end

app/models/widget.rb
class Widget < Scrivito::BasicWidget
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cms_controller.rb
class CmsController < Spree::StoreController
  include Scrivito::ControllerActions

  layout 'spree/layouts/spree_application'

  def index
    @title = @obj.title
  end
end

app/controllers/homepage_controller.rb
class HomepageController < CmsController
end

app/controllers/page_controller.rb
class PageController < CmsController
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do

  include Scrivito::ControllerHelper
  before_action :load_product, only: [:show, :create_scrivito_obj]
  before_action :fetch_scrivito_object, only: [:show]
  
  def create_scrivito_obj
    ProductData.create_for(@product)
    redirect_to product_path(@product)
  end
  
  private
  
  def fetch_scrivito_object
    @obj =
      begin
        ProductData.find_for(@product)
      rescue Scrivito::ResourceNotFound
        # Nothing to do here
      end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/download/details.html.erb
<%= scrivito_medium_dialog do %>
  <%= scrivito_details_for do %>
    <%= scrivito_tag :div, @obj, :blob do %>
      <%= link_to @obj.description_for_editor, scrivito_path(@obj), :target => :blank %>
    <% end %>
  <% end %>

  <%= scrivito_details_for do %>
    <%= number_to_human_size @obj.meta_data[:content_length] %>
  <% end %>

  <%= scrivito_details_for "Tags" do %>
    <%= scrivito_tag :div, @obj, :tags %>
  <% end %>
<% end %>

app/views/headline_widget/show.html.erb
<%= scrivito_tag :h2, widget, :headline %>

app/views/headline_widget/thumbnail.html.erb
<%= scrivito_thumbnail HeadlineWidget.description_for_editor, :headline do %>
  A headline widget.
<% end %>

app/views/homepage/details.html.erb
<%= scrivito_medium_dialog do %>
  <%= scrivito_details_for "Title" do %>
    <%= scrivito_tag :div, @obj, :title %>
  <% end %>

  <%= scrivito_details_for "Tags" do %>
    <%= scrivito_tag :div, @obj, :tags %>
  <% end %>
<% end %>

app/views/homepage/index.html.erb
<%= scrivito_tag :h1, @obj, :title %>
<%= scrivito_tag :div, @obj, :body %>

app/views/homepage/thumbnail.html.erb
<%= scrivito_thumbnail Homepage.description_for_editor, :content %>

app/views/image/details.html.erb
<%= scrivito_medium_dialog do %>
  <%= scrivito_details_for do %>
    <%= scrivito_image_tag @obj %>
  <% end %>

  <%= scrivito_details_for do %>
    <% if @obj.meta_data[:width] && @obj.meta_data[:height]%>
      <div>
        <%= @obj.meta_data[:width] %> × <%= @obj.meta_data[:height] %> px
      </div>
    <% end %>

    <div>
      <%= number_to_human_size @obj.meta_data[:content_length] %>
    </div>
  <% end %>

  <%= scrivito_details_for "Tags" do %>
    <%= scrivito_tag :div, @obj, :tags %>
  <% end %>
<% end %>

app/views/image_widget/show.html.erb
<%= scrivito_image_tag widget, :image %>

app/views/image_widget/thumbnail.html.erb
<%= scrivito_thumbnail ImageWidget.description_for_editor, :image do %>
  A widget with an image.
<% end %>

app/views/page/details.html.erb
<%= scrivito_medium_dialog do %>
  <%= scrivito_details_for "Title" do %>
    <%= scrivito_tag :div, @obj, :title %>
  <% end %>

  <%= scrivito_details_for "Tags" do %>
    <%= scrivito_tag :div, @obj, :tags %>
  <% end %>

  <%= scrivito_details_for "Permalink" do %>
    <%= scrivito_tag :div, @obj, :_permalink %>
  <% end %>
<% end %>

app/views/page/thumbnail.html.erb
<%= scrivito_thumbnail Page.description_for_editor, :content %>

app/views/shared/_scrivito_footer.html.erb
<footer class="scrivito_content" data-hook>
  <%= scrivito_tag(:div, Obj.root, :footer) %>
</footer>

app/views/shared/_scrivito_header_logo.html.erb
<%= link_to scrivito_path (Obj.root) do %>
  <%= scrivito_image_tag Obj.root, :logo, {}, transform: { width: 150, height: 50 } %>
<% end %>

app/views/shared/_scrivito_main_nav_bar.html.erb
<li id="home-link" data-hook>
  <%= link_to Obj.root.display_title, scrivito_path(Obj.root) %>
</li>

<%= scrivito_tag_list :span, Obj.root, :toclist do |list, page| %>
  <%= list.tag :li do %>
    <%= link_to page.display_title, scrivito_path(page) %>
  <% end %>
<% end %>

<% if Obj.root.toclist.empty? && scrivito_in_editable_view? %>
  <span>(Hint: Click on the Scrivito icon to the right to create the first subpage.)</span>
<% end %>

app/views/shared/_scrivito_products_sidebar.html.erb
<%= scrivito_tag(:div, Obj.root, :products_sidebar) %>

app/views/solidus_products_widget/details.html.erb
<%= scrivito_large_dialog do %>
  <%= scrivito_details_for SolidusProductsWidget.description_for_editor do %>
    <%= scrivito_details_for "Products" do %>
      <%= scrivito_tag :div, widget, :product_ids, {data: {solidus_api_key: current_spree_user.spree_api_key}} %>
    <% end %>
  <% end %>
<% end %>

app/views/solidus_products_widget/show.html.erb
<% if widget.products.any? %>
  <%= render partial: 'spree/shared/products', locals: { products: widget.products } %>
<% else %>
  <p>
    No products selected. Edit widget properties to select products to display here.
  </p>
<% end %>

app/views/solidus_products_widget/thumbnail.html.erb
<%= scrivito_thumbnail SolidusProductsWidget.description_for_editor %>

app/views/spree/products/show.html.erb
<% cache [I18n.locale, current_pricing_options, @product] do %>
<div data-hook="product_show" itemscope itemtype="http://schema.org/Product">
<% @body_id = 'product-details' %>
  <section class="section-3">
    <div class="container">
      <div class="row">
        <div class="">
          <div class="row mrg-top-90">

            <div class="col-md-6">
              <div id="product-images" class="swiper-container gallery-screen no-pdd">
                <div class="swiper-wrapper">
                  <%= render partial: 'image' %>
                </div>
              </div>   
              <div class="swiper-container gallery-thumbs">
                <div class="swiper-wrapper">                 
                    <%= render partial: 'thumbnails' %>                  
                </div>
              </div>
                  <!-- <div data-hook="product_properties">
                    <%#= render partial: 'properties' %>
                  </div>

                  <div data-hook="promotions">
                    <%#= render partial: 'promotions' %>
                  </div> -->              
            </div>
                  
             
            <div class="col-md-6">                               
                  <h2 class="mrg-btm-30" itemprop="name"><%= @product.name %></h2>

                  <div itemprop="description" data-hook="description">
                    <p class="width-70 mrg-btm-30">
                      <%= product_description(@product) rescue Spree.t(:product_has_no_description) %>
                    </p>
                  </div>
                  <div id="cart-form" data-hook="cart_form">
                    <%= render partial: 'cart_form' %>
                  </div>
                <%#= render partial: 'taxons' %>                 
            </div>

            
          </div>
        </div>
      </div>

      <% if @obj %>
        <%= scrivito_tag :div, @obj, :body %>
      <% elsif scrivito_in_editable_view? %>
        <%= link_to "Provide product data", create_scrivito_obj_product_path(@product) ,method: 'POST'%>
      <% end %>
    </div>
  </section>
</div>
<% end %>

app/views/text_widget/show.html.erb
<%= scrivito_tag :div, widget, :text %>

app/views/text_widget/thumbnail.html.erb
<%= scrivito_thumbnail TextWidget.description_for_editor, :text do %>
  A widget for HTML content.
<% end %>